### ISSUE TITLE
cover doesn't exist

### ISSUE THREAD

**Issue by miqmago** [douglasduteil/isparta#118]
6.9.0 (babel-core 6.9.0)

The only command that worked for me:

./node_modules/.bin/babel-node ./node_modules/isparta/lib/cli/index.js cover ./node_modules/.bin/_mocha -- test/test.js --require babel-register

**Comment by miqmago** [comment]
Sorry I forgot the log, the issue is that when executing the command:

`./node_modules/.bin/babel-node ./node_modules/isparta/lib/cli/index.js cover ./node_modules/.bin/_mocha -- test/test.js --require babel-register`

It works, but I'm getting this error:

```
Transformation error; return original code
{ Error: Line 1: Unexpected token ILLEGAL
    at constructError (/home/travis/build/appfeel/path-reducer/node_modules/esprima/esprima.js:2406:21)
    at createError (/home/travis/build/appfeel/path-reducer/node_modules/esprima/esprima.js:2425:17)
    at unexpectedTokenError (/home/travis/build/appfeel/path-reducer/node_modules/esprima/esprima.js:2500:13)
    at throwUnexpectedToken (/home/travis/build/appfeel/path-reducer/node_modules/esprima/esprima.js:2504:15)
    at scanPunctuator (/home/travis/build/appfeel/path-reducer/node_modules/esprima/esprima.js:842:13)
    at advance (/home/travis/build/appfeel/path-reducer/node_modules/esprima/esprima.js:1621:16)
    at peek (/home/travis/build/appfeel/path-reducer/node_modules/esprima/esprima.js:1708:78)
    at parseProgram (/home/travis/build/appfeel/path-reducer/node_modules/esprima/esprima.js:5502:9)
    at Object.parse (/home/travis/build/appfeel/path-reducer/node_modules/esprima/esprima.js:5689:23)
    at Instrumenter.instrumentSync (/home/travis/build/appfeel/path-reducer/node_modules/isparta/lib/instrumenter.js:68:39)
  lineNumber: 1,
  description: 'Unexpected token ILLEGAL',
  index: 0 }
```
