### ISSUE TITLE
TypeError: Cannot set property 'covered' of undefined

### ISSUE THREAD

**Issue by pinktrink** [douglasduteil/isparta#21]
I've set up the custom fork and all, and it seems to be generating coverage for a few files, but then it bombs out with this error:

```
TypeError: Cannot set property 'covered' of undefined
    at /x/x/x/x/x/x/node_modules/istanbul/lib/report/html.js:175:66
    at Array.forEach (native)
    at annotateLines (/x/x/x/x/x/x/node_modules/istanbul/lib/report/html.js:173:28)
    at HtmlReport.Report.mix.writeDetailPage (/x/x/x/x/x/x/node_modules/istanbul/lib/report/html.js:395:9)
    at /x/x/x/x/x/x/node_modules/istanbul/lib/report/html.js:461:26
    at SyncFileWriter.extend.writeFile (/x/x/x/x/x/x/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/x/x/x/x/x/x/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /x/x/x/x/x/x/node_modules/istanbul/lib/report/html.js:460:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/x/x/x/x/x/x/node_modules/istanbul/lib/report/html.js:454:23)
```

Any ideas?

**Comment by douglasduteil** [comment]
nope...

**Comment by mwq27** [comment]
Do you only get that error when you use 'html' as the coverage reporter?  Have you tried text or something else?  I get the same error when going for 'html'.

**Comment by pinktrink** [comment]
I'll try something else and report back.

**Comment by pinktrink** [comment]
Hm. It randomly started working. I guess I'll act like this didin't happen.

**Comment by douglasduteil** [comment]
Alright.
