### ISSUE TITLE
As of 3.0.3, isparta is not recognized as a valid module.

### ISSUE THREAD

**Issue by pinktrink** [douglasduteil/isparta#33]
`npm install` output for isparta:

```
isparta@3.0.3 node_modules/isparta
├── which@1.0.9
├── nomnom@1.8.1 (chalk@0.4.0, underscore@1.6.0)
├── lodash.partial@3.1.0 (lodash._replaceholders@3.0.0, lodash.restparam@3.6.0, lodash._createwrapper@3.0.3)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── esprima@2.1.0
├── source-map@0.4.2 (amdefine@0.1.0)
├── escodegen@1.6.1 (esutils@1.1.6, estraverse@1.9.3, optionator@0.5.0, source-map@0.1.43, esprima@1.2.5)
└── babel-core@5.0.10 (slash@1.0.0, to-fast-properties@1.0.1, shebang-regex@1.0.0, trim-right@1.0.0, path-is-absolute@1.0.0, fs-readdir-recursive@0.1.1, leven@1.0.1, private@0.1.6, globals@6.4.1, esutils@1.1.6, estraverse@1.9.3, line-numbers@0.2.0, convert-source-map@0.5.1, is-integer@1.0.4, output-file-sync@1.1.0, js-tokens@1.0.0, debug@2.1.3, chalk@1.0.0, detect-indent@3.0.1, ast-types@0.7.2, repeating@1.1.2, minimatch@2.0.4, source-map-support@0.2.10, regexpu@1.1.2, regenerator-babel@0.8.13-2, lodash@3.6.0, core-js@0.8.1)
```

Error when trying a manual require:
```
> require('isparta')
Error: Cannot find module 'isparta'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
```

**Comment by douglasduteil** [comment]
Hum... Dunno why 'cause it's working for me and [travis](https://travis-ci.org/douglasduteil/study-node-path-es6/jobs/57027484#L166)...
Hoping that it will naturally be solved somehow like [back then](https://github.com/douglasduteil/isparta/issues/21#issuecomment-82687268) :)
@pinktrink  Let me know if you're still difficulties accessing to it.

**Comment by deepsweet** [comment]
make sure that you have `./node_modules/isparta/lib/` folder.
most likely you just need to reinstall it because you have tried to install it from git branch or something (`lib/` appears only after prepublish npm script).

**Comment by cvbuelow** [comment]
I'm seeing this error too and I don't have `./node_modules/isparta/lib/`. How do I get that?

**Comment by deepsweet** [comment]
you should re-install isparta from npm.

**Comment by jhorwit2** [comment]
I just created a brand new npm project using `npm init` and still do not have the `lib` folder after installing via npm. Any suggestions?

**Comment by bendrucker** [comment]
You might try `npm cache clean isparta`. You can verify the package is published properly by grabbing and extracting the tarball directly: http://registry.npmjs.org/isparta/-/isparta-3.0.3.tgz

**Comment by douglasduteil** [comment]
I'm closing this for now. Feel free to reopen it if you still have this issue.

**Comment by sap9433** [comment]
Though I have isparta installed ` "isparta": "^4.0.0",` 

I'm getting following error 
```
07 01 2016 16:47:43.132:DEBUG [plugin]: Loading plugin isparta.
/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:116
        var type = module[name][0];
                               ^

TypeError: Cannot read property '0' of undefined
    at /usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:116:32
    at Array.forEach (native)
    at /usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:115:27
    at Array.forEach (native)
    at new Injector (/usr/local/lib/node_modules/karma/node_modules/di/lib/injector.js:104:11)
    at new Server (/usr/local/lib/node_modules/karma/lib/server.js:90:20)
    at Object.exports.run (/usr/local/lib/node_modules/karma/lib/cli.js:231:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```
