### ISSUE TITLE
Am I still supposed to use the karma-coverage fork?

### ISSUE THREAD

**Issue by lukescott** [douglasduteil/isparta#38]
I'm trying karma coverage 0.3.1. [karma-coverage/130](karma-coverage/pull/130) was merged, but I'm getting the following error:

```
ERROR [coverage]: [TypeError: Cannot read property 'split' of undefined]
TypeError: Cannot read property 'split' of undefined
    at HtmlReport.Report.mix.writeDetailPage (/Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:395:30)
    at /Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:472:26
    at SyncFileWriter.extend.writeFile (/Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/util/file-writer.js:57:9)
    at FileWriter.extend.writeFile (/Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/util/file-writer.js:147:23)
    at /Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:471:24
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:465:23)
    at /Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:467:22
    at Array.forEach (native)
    at HtmlReport.Report.mix.writeFiles (/Users/lukescott/Documents/Projects/webconnex/director-js/node_modules/istanbul/lib/report/html.js:465:23)
```

It works with the fork though.

**Comment by douglasduteil** [comment]
I don't know... I will be testing this tonight

**Comment by cgmartin** [comment]
+1 Also getting exact error/stacktrace using karma-coverage@0.3.1

**Comment by rossbayer** [comment]
+1 I can report the same, works fine with fork, does not work against karma-coverage@0.3.1

**Comment by kentcdodds** [comment]
Everything is working fine for me without using the fork.

**Comment by cgmartin** [comment]
Not seeing this error now using karma-coverage@0.4.2

**Comment by Dignifiedquire** [comment]
No need for the fork anymore :) If there is the need change something to make it work, please open a PR/issue on karma/karma-coverage

**Comment by rovolution** [comment]
> No need for the fork anymore :) If there is the need change something to make it work, please open a PR/issue on karma/karma-coverage

If this is the case, could you update the README to indicate this @douglasduteil? 

Thanks!

**Comment by Sjors** [comment]
I can confirm I didn't need the douglasduteil/karma-coverage#next fork.

**Comment by martinmicunda** [comment]
@Sjors what version of `karma-coverage` are you using? I have still problem that my code is showing as ES5 and not ES6 (I have opened [issue](https://github.com/karma-runner/karma-coverage/issues/175) in `karma-coverage` plugin)

**Comment by onlywei** [comment]
I just tried to switch to `karma-coverage@0.5.2` and my code started showing ES5 instead of ES6. Looks like we still need the fork?

**Comment by blittle** [comment]
Having the same problem with 0.5.3. I see ES5 code instead of ES6.

**Comment by AdamWillden** [comment]
Is this a problem with isparta or karma-coverage? +1 to fixing this either way.

**Comment by omichelsen** [comment]
+1
