### ISSUE TITLE
isparta binary doesn't work because methods are nested under 'default'

### ISSUE THREAD

**Issue by tmcw** [douglasduteil/isparta#4]
[Here the methods of nomnom are nested under default](https://github.com/douglasduteil/isparta/blob/master/lib/cli.js#L3-7) and [here isparta tries to access them from the root](https://github.com/douglasduteil/isparta/blob/master/lib/cli.js#L36).

As a result:

```
/usr/local/lib/node_modules/isparta/lib/cli.js:36
nomnom.command("cover").help("transparently adds coverage information to a nod
       ^
TypeError: Object #<Object> has no method 'command'
    at Object.<anonymous> (/usr/local/lib/node_modules/isparta/lib/cli.js:36:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/isparta/bin/isparta:2:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by douglasduteil** [comment]
Oops right
