### ISSUE TITLE
isparta doesn't forward exit code in case of failures

### ISSUE THREAD

**Issue by n1k0** [douglasduteil/isparta#48]
The docs give this line as an example:

```
babel-node node_modules/.bin/isparta cover --report text --report lcovonly --root ./src node_modules/.bin/_mocha
```

The problem is it seems it doesn't forward the test exit status code properly, so we get successes instead of failures:

![screen shot 2015-07-16 at 10 35 36](https://cloud.githubusercontent.com/assets/41547/8718696/b4c2edaa-2ba6-11e5-8a2e-2e989d46117d.png)

isparta v.3.0.3

**Comment by n1k0** [comment]
This is also reproducible on the isparta repository itself — which test suite is failing as well btw:

```
$ babel-node bin/isparta cover --report text --report html node_modules/.bin/_mocha -- --reporter dot
Transformation error; return original code
{ [SyntaxError: /Users/niko/Sites/isparta/node_modules/mocha/bin/_mocha: 'return' outside of function (392:2)]
  pos: 9902,
  loc: { line: 392, column: 2 },
  raisedAt: 9908,
  _babel: true,
  codeFrame: '  390 |   \u001b[32m}\u001b[39m\u001b[34m\u001b[1m)\u001b[22m\u001b[39m\u001b[1m;\u001b[22m\n  391 | \n> 392 |   \u001b[36mreturn\u001b[39m\u001b[1m;\u001b[22m\n      |   ^\n  393 | \u001b[32m}\u001b[39m\n  394 | \n  395 | \u001b[90m// load\u001b[39m' }


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․

  33 passing (121ms)
  14 failing

  1) Isparta instrumenter when es6-classes should localize the 1st fn:

      Expect the 1st fns to be deeply equal.
      + expected - actual

       {
      -  "line": 9
      +  "line": 3
         "loc": {
           "end": {
             "column": 0
             "line": 0

      at Context.locationIt (test/index.spec.js:119:24)

  2) Isparta instrumenter when es6-classes should localize the 2nd fn:

      Expect the 2nd fns to be deeply equal.
      + expected - actual

       {
      -  "line": 9
      +  "line": 5
         "loc": {
           "end": {
             "column": 0
             "line": 0
             "column": 0
             "line": 0
           }
         }
      -  "name": "defineProperties"
      +  "name": "(anonymous_2)"
         "skip": true
       }

      at Context.locationIt (test/index.spec.js:119:24)

  3) Isparta instrumenter when es6-classes should localize the 3rd fn:

      Expect the 3rd fns to be deeply equal.
      + expected - actual

       {
      -  "line": 9
      +  "line": 5
         "loc": {
           "end": {
             "column": 0
             "line": 0
             "column": 0
             "line": 0
           }
         }
      -  "name": "(anonymous_3)"
      +  "name": "defineProperties"
         "skip": true
       }

      at Context.locationIt (test/index.spec.js:119:24)

  4) Isparta instrumenter when es6-classes should localize the 4th fn:

      Expect the 4th fns to be deeply equal.
      + expected - actual

       {
      -  "line": 11
      +  "line": 5
         "loc": {
           "end": {
             "column": 0
             "line": 0
             "column": 0
             "line": 0
           }
         }
      -  "name": "_classCallCheck"
      +  "name": "(anonymous_4)"
         "skip": true
       }

      at Context.locationIt (test/index.spec.js:119:24)

  5) Isparta instrumenter when es6-classes should localize the 5th fn:

      Expect the 5th fns to be deeply equal.
      + expected - actual

       {
      -  "line": 13
      +  "line": 12
         "loc": {
           "end": {
             "column": 10
             "line": 3

      at Context.locationIt (test/index.spec.js:119:24)

  6) Isparta instrumenter when es6-classes should localize the 6th fn:

      Expect the 6th fns to be deeply equal.
      + expected - actual

       {
      -  "line": 14
      +  "line": 13
         "loc": {
           "end": {
             "column": 0
             "line": 0

      at Context.locationIt (test/index.spec.js:119:24)

  7) Isparta instrumenter when es6-classes should localize the 7th fn:

      Expect the 7th fns to be deeply equal.
      + expected - actual

       {
      -  "line": 20
      +  "line": 19
         "loc": {
           "end": {
             "column": 10
             "line": 4

      at Context.locationIt (test/index.spec.js:119:24)

  8) Isparta instrumenter when es6-classes should localize the 8th fn:

      Expect the 8th fns to be deeply equal.
      + expected - actual

       {
      -  "line": 25
      +  "line": 24
         "loc": {
           "end": {
             "column": 13
             "line": 8

      at Context.locationIt (test/index.spec.js:119:24)

  9) Isparta instrumenter when es6-classes should localize the 9th fn:

      Expect the 9th fns to be deeply equal.
      + expected - actual

       {
      -  "line": 30
      +  "line": 29
         "loc": {
           "end": {
             "column": 19
             "line": 12

      at Context.locationIt (test/index.spec.js:119:24)

  10) Isparta instrumenter when es6-classes should localize the 1st branch:

      Expect the 1st branchs to be deeply equal.
      + expected - actual

       {
      -  "line": 9
      +  "line": 3
         "locations": [
           {
             "end": {
               "column": 0
               "line": 0
             }
           }
         ]
      -  "type": "binary-expr"
      +  "type": "if"
       }

      at Context.locationIt (test/index.spec.js:119:24)

  11) Isparta instrumenter when es6-classes should localize the 2nd branch:

      Expect the 2nd branchs to be deeply equal.
      + expected - actual

       {
      -  "line": 9
      +  "line": 5
         "locations": [
           {
             "end": {
               "column": 0
               "line": 0
             }
           }
         ]
      -  "type": "if"
      +  "type": "binary-expr"
       }

      at Context.locationIt (test/index.spec.js:119:24)

  12) Isparta instrumenter when es6-classes should localize the 3rd branch:

      Expect the 3rd branchs to be deeply equal.
      + expected - actual

       {
      -  "line": 9
      +  "line": 5
         "locations": [
           {
             "end": {
               "column": 0

      at Context.locationIt (test/index.spec.js:119:24)

  13) Isparta instrumenter when es6-classes should localize the 4th branch:

      Expect the 4th branchs to be deeply equal.
      + expected - actual

       {
      -  "line": 9
      +  "line": 5
         "locations": [
           {
             "end": {
               "column": 0

      at Context.locationIt (test/index.spec.js:119:24)

  14) Isparta instrumenter when es6-classes should localize the 5th branch:

      Expect the 5th branchs to be deeply equal.
      + expected - actual

       {
      -  "line": 11
      +  "line": 5
         "locations": [
           {
             "end": {
               "column": 0

      at Context.locationIt (test/index.spec.js:119:24)



================================================================================
Writing coverage object [/Users/niko/Sites/isparta/coverage/coverage.json]
Writing coverage reports at [/Users/niko/Sites/isparta/coverage]
================================================================================
------------------|----------|----------|----------|----------|----------------|
File              |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------------|----------|----------|----------|----------|----------------|
 src/             |    99.49 |    92.59 |      100 |    97.73 |                |
  instrumenter.js |    99.43 |    92.96 |      100 |     97.5 |             40 |
  isparta.js      |      100 |       90 |      100 |      100 |                |
------------------|----------|----------|----------|----------|----------------|
All files         |    99.49 |    92.59 |      100 |    97.73 |                |
------------------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 99.49% ( 196/197 ), 37 ignored
Branches     : 92.59% ( 75/81 ), 32 ignored
Functions    : 100% ( 36/36 ), 3 ignored
Lines        : 97.73% ( 43/44 )
================================================================================
 niko@n1k0-moz ~/Sites/isparta
$ echo $?
0
```

**Comment by n1k0** [comment]
Minimal reproducible test case:

```
 niko@n1k0-moz ~/Sites/isparta
$ cat fail.js
process.exit(1)
 niko@n1k0-moz ~/Sites/isparta
$ babel-node bin/isparta cover fail.js -- --reporter dot && echo $?
================================================================================
Writing coverage object [/Users/niko/Sites/isparta/coverage/coverage.json]
Writing coverage reports at [/Users/niko/Sites/isparta/coverage]
================================================================================

=============================== Coverage summary ===============================
Statements   : 100% ( 1/1 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 1/1 )
================================================================================
0
```

**Comment by n1k0** [comment]
After investigating the issue for a little while, I came with this as a replacement for `runCommandFn` in `cli.js`:

```js
function runCommandFn() {
    process.env.running_under_istanbul = 1;
    var p = (0, _child_process.spawn)('node', [cmd].concat(cmdArgs));
    p.stdout.on('data', function (data) {
      process.stdout.write(data);
    });
    p.stderr.on('data', function (data) {
      process.stderr.write(data);
    });
    p.on('close', function (code) {
      callback(code === 0 ? null : 'Command exited with ' + code);
    });
  }
```

Sadly, it fails at transpiling babel code and lose coloration. I'm leaving all this here, feel free to come with a solution; for now I'll have to disable coverage reporting as failing green builds are simply unacceptable to us.

**Comment by emmenko** [comment]
Having same issue. Is there a solution or fix for that already or not yet?

Thanks

**Comment by jedmao** [comment]
@n1k0 passing `{ stdio: 'inherit' }` to the spawn command options gives you colors.
