### ISSUE TITLE
Object.assign is not a function

### ISSUE THREAD

**Issue by ScreenDriver** [douglasduteil/isparta#62]
Since https://github.com/douglasduteil/isparta/issues/55#issuecomment-135981404 and pull request #61 I get a 

```sh
Loading config: /Users/me/Development/my_project/.istanbul.yml
/Users/me/Development/my_project/node_modules/isparta/lib/cli.js:197
    _istanbul.hook.hookRequire(matchFn, transformer, Object.assign({ verbose:
                                                            ^
TypeError: Object.assign is not a function
    at prepareCoverage (/Users/me/Development/my_project/node_modules/isparta/lib/cli.js:197:61)
    at /Users/me/Development/my_project/node_modules/isparta/lib/cli.js:187:7
    at /Users/me/Development/my_project/node_modules/isparta/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /Users/me/Development/my_project/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at /Users/me/Development/my_project/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:363:13
    at /Users/me/Development/my_project/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:52:16
    at done (/Users/me/Development/my_project/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:248:21)
    at /Users/me/Development/my_project/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:44:16
    at /Users/me/Development/my_project/node_modules/isparta/node_modules/istanbul/node_modules/async/lib/async.js:360:17
```

I am using `iojs v2.5.0`

**Comment by ScreenDriver** [comment]
Ok, I've forgot to add a `babel-node node_modules/.bin/isparta...` to my build script.
