### ISSUE TITLE
TypeError with project based on gulp-angular Yeoman boilerplate

### ISSUE THREAD

**Issue by keithkml** [douglasduteil/isparta#70]
I installed isparta which made a lot of changes to my `package.json` - including `"karma-coverage": "douglasduteil/karma-coverage#next"`

However, now I can't run my tests at all. (Yes, `gulp test` worked flawlessly before.)

```
[10:37:35] Finished 'scripts:test' after 7.73 s
[10:37:35] Starting 'test'...
[BABEL] Note: The code generator has deoptimised the styling of "./.tmp/serve/app/index.module.js" as it exceeds the max of "100KB".
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: 'undefined' is not an object (evaluating 'u._')
  at /Users/keith/Code/whamserver-prod/src/apps/DefaultWithGulp/.tmp/serve/app/index.module.js:9


[10:37:41] 'test' errored after 6.22 s
[10:37:41] Error: Failed 1 tests.
    at /Users/keith/Code/whamserver-prod/src/apps/DefaultWithGulp/gulp/unit-tests.js:41:22
    at removeAllListeners (/Users/keith/Code/whamserver-prod/src/apps/DefaultWithGulp/node_modules/karma/lib/server.js:329:7)
    at Server.<anonymous> (/Users/keith/Code/whamserver-prod/src/apps/DefaultWithGulp/node_modules/karma/lib/server.js:340:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1518:8)
    at doNTCallback1 (node.js:418:9)
    at process._tickCallback (node.js:340:17)
Keiths-MacBook-Pro:DefaultWithGulp keith$ 
```

**Comment by douglasduteil** [comment]
Similar to  #38 N
