### ISSUE TITLE
SyntaxError - Unable to run isparta.

### ISSUE THREAD

**Issue by niba** [douglasduteil/isparta#80]
I'm trying to run isparta with mocha using the following command:
`babel-node node_modules/.bin/isparta cover node_modules/.bin/_mocha`

The result is 

    project\node_modules\.bin\isparta:4
    case `uname` in
    ^^^^

    SyntaxError: Unexpected token case
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:413:25)
        at Module._extensions..js (module.js:452:10)
        at Object.require.extensions.(anonymous function) [as .js] (
    project\node_modules\babel-core\lib\api\register\node.js:214:7)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:475:10)
        at Object.<anonymous> (project\node_modules\babel\lib\_babel-node.js:144:25)
        at Module._compile (module.js:434:26)
        at Object.Module._extensions..js (module.js:452:10)

I use Windows, Node 4.2.1 and Babel 5.8.23
What I'm doing wrong?

**Comment by douglasduteil** [comment]
Might be fixed with the new release https://github.com/douglasduteil/isparta/releases/tag/v3.2.0
Feel free to reopen it if you still have this issue.

**Comment by niba** [comment]
Unfortunately there is still an issue with running

**Comment by stkrzysiak** [comment]
@douglasduteil I am experiencing this as well, it seems to be windows specific.  A suggestion I saw elsewhere[1] to resolve this was to remove the 'node' in the beginning, in our case this would be babel-node.  When I remove that I am told something along the lines of unknown stage option in babelrc.  This would make sense since we need babel here, or do we?

[1] https://github.com/electronjs/electron-rebuild/issues/22

**Comment by barrett-vegas-com** [comment]
I got around this by using the following:
```
babel-node node_modules/isparta/bin/isparta cover node_modules/mocha/bin/_mocha
```
